### ISSUE TITLE
[Auth,User] Duplicate username from users registration.

### ISSUE THREAD

**Issue by katisd** [meeorder/meeorder-backend#116]
The user shouldn't be able to register with the same username.
And should we have rules for usernames? (eg. at least 8 characters long including 1 uppercase and 1 number)
![image](https://github.com/meeorder/meeorder-backend/assets/90249534/3a8bd6fa-7008-4dfa-b325-2a50d423ccca)

**Comment by lazykern** [comment]
Of course, there must be some constraints for username
- Minimum length of 4-6, I prefer 4
- Maximum length of 32
- Must contain only alphanumeric characters
- Must not contain special characters, including white space 

Including both uppercase and lowercase might not be necessary. Although, while checking for duplicate username, it must be case insensitive.
