### ISSUE TITLE
Get all menus always return empty array

### ISSUE THREAD

**Issue by ishiasaka** [meeorder/meeorder-backend#127]
![image](https://github.com/meeorder/meeorder-backend/assets/40362631/88c13270-53b6-4ffb-a7f2-c583e8ee445d)

**Comment by ishiasaka** [comment]
<img width="1395" alt="image" src="https://github.com/meeorder/meeorder-backend/assets/40362631/729a7b06-cb7d-46db-8a04-0f09ac2e3349">


Data lost all at stage 10
https://github.com/meeorder/meeorder-backend/blob/e858c043d41583080e9216a055f13788b9de4d26/src/menus/menus.service.ts#L70

**Comment by namirinz** [comment]
ข้อมูล Category  ใน DB หายปะ เวลา aggregate เข้าไม่เจอเลยโล่ง
