### ISSUE TITLE
[Orders] Orders from finished session shouldn't be include in active orders

### ISSUE THREAD

**Issue by katisd** [meeorder/meeorder-backend#202]
e.g โต๊ะใหม่123 สั่งต้มยำกุ้ง
![image](https://github.com/meeorder/meeorder-backend/assets/90249534/b60eecf8-61d3-45fa-86bf-0e210ec043ed)

หลังจาก ปิด Session ของ โต๊ะใหม่123
![image](https://github.com/meeorder/meeorder-backend/assets/90249534/618e283c-e7d6-4eab-bfb5-5bfc371ce7ed)

**Comment by vjumpkung** [comment]
fixed
