### ISSUE TITLE
Auth token extractJWT.

### ISSUE THREAD

**Issue by katisd** [meeorder/meeorder-backend#92]
Backend set  JWT as cookies, But extract from Bearier authorization.
in src\auth\auth.guard.ts
![image](https://github.com/meeorder/meeorder-backend/assets/90249534/6b21523b-ed2c-44c4-a856-b25d50c61f96)

Frontend Request Header
![image](https://github.com/meeorder/meeorder-backend/assets/90249534/c64f1a4e-bc2c-46b2-b4f8-15f0e31392cb)

This may solve it.
![image](https://github.com/meeorder/meeorder-backend/assets/90249534/f7ac412e-bc43-4785-bae3-4dfb0a79c87d)

**Comment by katisd** [comment]
When unauthorized shouldn't it be 401:Unauthorized?
![image](https://github.com/meeorder/meeorder-backend/assets/90249534/d8968ce9-5fca-4653-bcfa-2cef2d3f670c)

**Comment by ishiasaka** [comment]
No `Authorization` In header
